name: DevelopmentPipeline

on: 
  push: 
    branches: [develop]

jobs: 
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Install Dependencies ..."
          npm install
      - name: Run Linter
        run: |
          echo "Running Linting tests ..."
          npm run lint
        env:
          CI: true
